### PR TITLE
API base controller

### PR DESCRIPTION
**Pull request by flyingluscas**
Added a base controller to make it easier to return responses without worrying about the status code, and it gets more readable too.

### CODE REVIEW

**Comment by hernandev** [comment]
Great job, I personally  hate using the numbers inside the code

:+1:

**Comment by flyingluscas** [comment]
@hernandev Me too hehehehhe :)

**Comment by vedovelli** [comment]
+1 thanks a lot!

**Comment by vedovelli** [comment]
@cristianopacheco Please mind the LoginController was affected by this PR. Don't forget to update from upstream before making your changes! Thanks!

**Pull request merged**
