### PR TITLE
Returns the user using the transformer

### PR DESCRIPTION
**Pull request by jaonoctus**

### CODE REVIEW

**Review by flyingluscas — APPROVED** [review]
@JaoNoctus nice work, I've totally forgot the returned user in the AuthController, thanks!

**Comment by flyingluscas** [comment]
@vinicius73 @vedovelli will this change affect in any way the client side?

**Comment by jaonoctus** [comment]
@flyingluscas @vinicius73  @vedovelli
I guess so, because the json response structure has changed _(but at least now it's the right way)_.

Before:
```php
[
    'token',
    'token_ttl',
    'user' => [
        'id',
        'name',
        'email',
    ],
]
```

After:
```php
[
    'token',
    'token_ttl',
    'user' => [
        'data' => [
            'id',
            'name',
            'email',
        ],
    ],
]
```

**Comment by flyingluscas** [comment]
@JaoNoctus I think so too

**Comment by vedovelli** [comment]
@JaoNoctus Thanks for this PR! I'll follow up from this point on!

**Comment by vinicius73** [comment]
commit 6228fa9917d8d38af1a24b2bbe8a940f91eb52f6  fix BC from this PR

**Pull request merged**
