### PR TITLE
Handling all exceptions with a JSON response

### PR DESCRIPTION
**Pull request by flyingluscas**
Handling all exceptions with a JSON response, that way the controller doesn't have to use try catch on every method.

### CODE REVIEW

**Comment by vedovelli** [comment]
@flyingluscas one quick question: returning a 500 error when the user is not authenticated is the best way? To my knowledge 500 errors are server errors.

**Comment by flyingluscas** [comment]
@vedovelli good point, I'm checking if is a HttpException to use the appropriate status code, but the AuthenticationException doesn't use the HttpException, let me see how I can fix this here ok

**Comment by flyingluscas** [comment]
@vedovelli ok, I've made some alterations, tested and it seems ok now, but I dont like the size of method **handleExceptionJsonResponse**, what do you think?

**Comment by vedovelli** [comment]
@flyingluscas I'm OK with the method size. But I think it deserves comments to explain each block. Remember this application is also a source of knowledge. Thanks!

**Comment by vedovelli** [comment]
Thanks a lot!

**Comment by flyingluscas** [comment]
No, thank you sir, from now on I'll comment more my code :D

**Pull request merged**
